Final Project/myteam/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView


urlpatterns = [
    path("", views.home, name="home"),
    path("home", views.home, name="home"),
    path("register", views.Register.as_view(), name="register"),
    path("login", LoginView.as_view(), name="login"),
    path("logout_view", views.logout_view, name="logout_view"),
    path("profile", views.profile, name="profile"),
    path("profile/<profile_id>", views.otherprofile, name="otherprofile"),
    path("edit_profile", views.edit_profile, name="edit_profile"),
    path("clubregistration", views.clubregistration, name="clubregistration"),
#     path("about", views.about, name="about"),
#     path("register", views.Register.as_view(), name="register"),
#     path("login", LoginView.as_view(), name="login"),
#     path("logout_view", views.logout_view, name="logout_view"),
#     path("profile", views.profile, name="profile"),
]

Final Project/myteam/club/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("clubs", views.clubs, name="clubs"),
    path("clubs/<club_id>/details", views.club_details, name="club_details"),
    path("clubs/<club_id>/fixtures", views.club_fixtures, name="club_fixtures"),
    path("clubs/<club_id>/fixtures/add_fixture", views.add_fixture, name="add_fixture"),
    path("clubs/<club_id>/fixtures/player_availability", views.player_availability, name="player_availability"),
    path("clubs/<club_id>/squad", views.club_squad, name="club_squad"),
    path("clubs/<club_id>/fixtures/<fixture_id>/cancel_fixture", views.cancel_fixture, name="cancel_fixture"),
    path("clubs/<club_id>/fixtures/<fixture_id>/edit_fixture", views.edit_fixture, name="edit_fixture"),
    path("clubs/<club_id>/fixtures/<fixture_id>/select_team", views.select_team, name="select_team"),
    path("clubs/<club_id>/fixtures/<fixture_id>/tactics", views.tactics, name="tactics"),
    path("clubs/<club_id>/fixtures/<fixture_id>/post_match_stats", views.post_match_stats, name="post_match_stats"),
    path("clubs/<club_id>/results", views.results, name="results"),
    path("clubs/<club_id>/player_registration", views.player_registration, name="player_registration"),
    path("clubs/<club_id>/join_club", views.join_club, name="join_club"),
    path("clubs/<club_id>/edit_club_details", views.edit_club_details, name="edit_club_details"),
]

Final Project/myteam/account/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    ROLE_CHOICES = [
        ('Manager', 'Manager'),
        ('Player', 'Player'),
        ('Player-Manager', 'Player-Manager'),
    ]
    POSITION_CHOICES = [
        ('Goalkeeper', 'Goalkeeper'),
        ('Defender', 'Defender'),
        ('Midfielder', 'Midfielder'),
        ('Attacker', 'Attacker'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(default=None, null=True, max_length=30)
    last_name = models.CharField(default=None, null=True, max_length=30)
    role = models.CharField(choices=ROLE_CHOICES, max_length=20, default=None, null=True)
    position = models.CharField(choices=POSITION_CHOICES, max_length=12, default=None, null=True)
    email = models.EmailField(default=None, null=True)
    phone = models.IntegerField(default=None, null=True)
    image = models.ImageField(upload_to='gallery',default='gallery/football.png', null=True)

    def __str__(self):
        if self.first_name and self.last_name:
            return (self.first_name + " " + self.last_name)
        else:
            return self.user.username

class Club(models.Model):
    name = models.CharField(default=None, max_length=50)
    logo = models.ImageField(null=True)
    manager = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='manager')
    players = models.ManyToManyField(Profile)
    password = models.CharField(max_length=20)

Final Project/myteam/account/forms.py
from django.forms import ModelForm, Form
from django import forms
from .models import Profile, Club

class CreateProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "role", "position", "email", "phone", "image"]
        labels = {
            "first_name": "First Name",
            "last_name": "Last Name",
            "role": "Role",
            "position": "Position",
            "email": "Email Address",
            "phone": "Phone Number",
            "image": "Upload your profile picture",
        }

class RegisterClubForm(ModelForm):
    class Meta:
        model = Club
        exclude = ['players', 'manager']


class RegisterPlayerForm(Form):
    fields = ["Club", "Password"]
    labels = {
        "club": "Club",
        "password": "Password",
    }

Final Project/myteam/account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout
from .forms import CreateProfileForm, RegisterClubForm, RegisterPlayerForm
from .models import Profile, Club
from user_messages.models import Message
from django.contrib.auth.models import User

# Create your views here.

def home(request):
    context = {
        'title': "Home",
        'heading': "Welcome to MyTeam",
        'summary': "Site for all amateur football team needs.",
    }
    return render(request, "home.html", context)

def profile(request):
    profile = Profile.objects.get_or_create(user=request.user)
    context = {
        'title': "Profile",
        'heading': "Profile Page",
        'clubs': Club.objects.filter(manager=request.user.profile),
        'player_clubs': Club.objects.filter(players=request.user.profile),
        'user_messages': Message.objects.filter(receiver=request.user.profile),
        'num_unread_messages': Message.objects.filter(receiver=request.user.profile, status='Unread').count(),
        'sent_messages': Message.objects.filter(sender=request.user.profile),
        'form': CreateProfileForm(),
    }
    if request.method == 'POST':
        form = CreateProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = profile
            profile.save()
            return render(request, "profile.html", context)

    return render(request, "profile.html", context)

def otherprofile(request, profile_id):
    player = get_object_or_404(Profile, id=profile_id)
    if request.user.id == player.user.id:
        return redirect("profile")
    else:
        context = {
            'title': "Someone Else Profile",
            'heading': "Someone Else Profile",
            'player': player,
            'player_clubs': Club.objects.filter(players=player.user.profile),
        }
        return render(request, "otherprofile.html", context)


def edit_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    context = {
        'title': "Edit Profile Details",
        'heading': "Edit Profile",
        'profile': profile,
        'form': CreateProfileForm(request.POST or None, instance=profile)
    }
    if request.method == 'POST':
        form = CreateProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("profile")
    return render(request, "editprofile.html", context)


def clubregistration(request):
    context = {
        'title': "Register Club",
        'heading': "Register Your Team",
        'form': RegisterClubForm(),
    }
    if request.method == 'POST':
        form = RegisterClubForm(request.POST, request.FILES)
        if form.is_valid():
            club = form.save(commit=False)
            club.manager = request.user.profile
            club.save()
            return render(request, "profile.html", context)

    return render(request, "clubregistration.html", context)



def clubs(request, club_id):
    club = get_object_or_404(Club, id=club_id)
    context = {
        'title': "Club Details",
        'heading': club.name,
        'club': club,
    }
    return render(request, "clubdetails.html", context)



class Register(CreateView):
    form_class = UserCreationForm
    template_name = "registration/register.html"
    success_url = "login"

    def form_valid(self, form):
        out = super().form_valid(form)
        return out


def logout_view(request):
    logout(request)
    return redirect("home")

Final Project/myteam/account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TITLE{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@500&display=swap" rel="stylesheet">

    <style>
    body {
    font-family: 'Rajdhani', sans-serif;
    height:100%;
    }
    .nav-item {
    font-size: 25px;
    margin: 20px;
    }
    #footer {
    background-image: url({% static 'banner.jpg' %});
    background-repeat: no-repeat;
    background-size: cover;
    width:100%;
    bottom:0;
    }

    #homejumbo {

    height: 650px;
    background-image: url({% static 'download.jpg' %});
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: contain;
    background-position: center 30px;
    color: white;

    }

    </style>


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-success sticky-top">
    <a class="navbar-brand" href="#"><img src="{% static 'football.png' %}" style="height: 25px;"> MyTeam</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav" style="position: absolute; left: 50%; transform: translatex(-50%);">
            <li class="nav-item active">
                <a class="nav-link" href="/home">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/clubs">Clubs</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/register">Register</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="/profile">My Profile</a>
            </li>
            {% for club in user.profile.club_set.all %}
            <li class="nav-item active">
                <a class="nav-link" href="/clubs/{{club.id}}/details">{{club.name}}</a>
            </li>
            {%endfor%}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'logout_view' %}">Logout</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
              </div>
            {% endfor %}
        {% endif %}
    <h1>{% block heading %}{% endblock %}</h1>



    {% block content %}
    THIS IS WHERE ALL THE OTHER STUFF WILL GO
    {% endblock %}
</div><br><br>

<div class="container">
<div class="text-center" id="footer" style="height: 300px;">
  <div class="container">
      <div style="height: 90px;"></div>
    <h1 class="display-4" ><a class="navbar-brand" href="#"><img src="{% static 'football.png' %}" style="height: 25px;"> MyTeam</a></h1>

    <p class="lead" style="font-size:30px;"><a href="/clubs">Clubs</a>
        {% if not user.is_authenticated %} | <a href="/clubs" >Login</a> | <a href="/register">Register</a> {% endif %}
         {% if user.is_authenticated %} | <a href="/profile">My Profile</a>{% for club in user.club_set.all %} | <a href="/clubs/{{club.id}}/details">{{club.name}}</a>{%endfor%}  | <a href="{% url 'logout_view' %}">Logout</a> {% endif %}
    </p>
      {% if user.is_authenticated %}
    <p class="lead" style="font-size:25px; color: green;">Logged in as {{ user.username | upper }}</p>
    {% endif %}
  </div>










<!--  </div>-->
<!--    <img src="{% static 'download.jpg' %}" style="width: 100%;">-->
<!--</div>-->
</body>
</html>

Final Project/myteam/account/templates/clubregistration.html
{% extends 'base.html' %}}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}
{% block heading %}{{heading}}{% endblock %}
{% block summary %}{{summary}}{% endblock %}
{% block content %}



<div class="row">
    <div class="col-4">

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Submit form">
</form>
    </div>
</div>
{% endblock %}

Final Project/myteam/account/templates/editprofile.html
{% extends 'base.html' %}}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}
{% block heading %}{{heading}}{% endblock %}
{% block summary %}{{summary}}{% endblock %}
{% block content %}

<div class="row">
    <div class="col-4">


<form method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Submit form">
</form><br>
    </div>
</div>


{% endblock %}

Final Project/myteam/account/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="jumbotron" id="homejumbo">
  <h1 class="display-4 text-center">MyTeam is MyHome</h1>
  <h3 class="text-center"><em>play together : stay together</em></h3>
</div>

<h1 class="display-4 text-center">Game On</h1>
<h3 class="text-center"><em>football team management made easy</em></h3><br>


<div class="card-deck">
  <div class="card shadow p-3 mb-5">
    <img class="card-img-top" src="media/gallery/clipboard.png" style="height: 300px; width: 80%;" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Register Your Club</h5>
      <p class="card-text">It takes 5 minutes to set up an account and register your club. Then you can explore all of our features. Managing your team has never been so easy!</p>
    </div>
    <div class="card-footer bg-success">
      <small class="text-muted"><a href="/register" style="color: white;">Sign Up Now</a></small>
    </div>
  </div>
  <div class="card shadow p-3 mb-5">
    <img class="card-img-top" src="media/gallery/calendar2.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Scheduling and Admin</h5>
      <p class="card-text">Manage your fixture schedule, arrange training sessions and plan team events. Your players will always have all the information they need.</p>
    </div>
    <div class="card-footer bg-success">
      <small class="text-muted"><a href="/clubs/1/fixtures" style="color: white;">See Example</a></small>
    </div>
  </div>
  <div class="card shadow p-3 mb-5">
    <img class="card-img-top" src="media/gallery/message.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Messaging</h5>
      <p class="card-text">Your squad will love how quick and simple it is for them to declare their availability and send you subscription fees. No more last-minute scrambling around for ringers!</p>
    </div>
    <div class="card-footer bg-success">
      <small class="text-muted"><a href="/compose_message/1" style="color: white;">See Example</a></small>
    </div>
  </div>
</div>
<br>
<div class="card-deck">
  <div class="card shadow p-3 mb-5">
    <img class="card-img-top" src="media/gallery/squad.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Manage Your Squad</h5>
      <p class="card-text">Set up your club profile in 5 minutes. Recruit players by sending them a link to join your team.</p>
    </div>
    <div class="card-footer bg-success">
      <small class="text-muted"><a href="/clubs/1/squad" style="color: white;">See Example</a></small>
    </div>
  </div>
  <div class="card shadow p-3 mb-5">
    <img class="card-img-top" src="media/gallery/team.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Pick Team and Set Tactics</h5>
      <p class="card-text">Pick the best team for each match based on availability and squad strength. Send out tactical instructions ahead of the game.</p>
    </div>
    <div class="card-footer bg-success">
      <small class="text-muted"><a href="/clubs/1/fixtures/3/tactics" style="color: white;">See Example</a></small>
    </div>
  </div>
  <div class="card shadow p-3 mb-5">
    <img class="card-img-top" src="media/gallery/stats.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Track Player Performances and Statistics</h5>
      <p class="card-text">Log match details after every game and build up an archive of club and player data over time.</p>
    </div>
    <div class="card-footer bg-success">
      <small class="text-muted"><a href="/clubs/1/fixtures/3/post_match_stats" style="color: white;">See Example</a></small>
    </div>
  </div>
</div>
<br>
{% endblock %}

Final Project/myteam/account/templates/otherprofile.html
{% extends 'base.html' %}}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}
{% block summary %}{{summary}}{% endblock %}
{% block content %}

<div class="card text-center">
  <div class="card-header">@{{player.user.username}}</div>
  <div class="card-body text-left">
      <div class="row">
          <div class="col-4">
              <img src="{{player.image.url}}" class="mx-auto d-block rounded" alt="..." style="width: 200px; height: 200px; object-fit: cover; right-margin: 100px;">
          </div>
          <div class="col-4">
              <h5 class="card-title">Details and Contact Information</h5>
              <table>
                  <tr>
                      <th>Name:</th>
                      <td>{{player.first_name}} {{player.last_name}}</td>
                  </tr>
                  <tr>
                      <th>Email Address:   </th>
                      <td>{{player.email}}</td>
                  </tr>
                  <tr>
                      <th>Role:</th>
                      <td>{{player.role}}</td>
                  </tr>
                  <tr>
                      <th>Position:</th>
                      <td>{{player.position}}</td>
                  </tr>
            </table>
          </div>
          <div class="col-4">
               <h5 class="card-title">{{player.first_name}}'s Clubs</h5>
              {% if clubs %}
              {% for club in clubs %}
                <a href="clubs/{{club.id}}/details" class="btn btn-warning btn-sm">{{club.name}} (Manager)</a><br><br>
              {% endfor %}
              {% endif %}
              {% if player_clubs %}
              {% for club in player_clubs %}
              <a href="/clubs/{{club.id}}/details" class="btn btn-success btn-sm">{{club.name}} (Player)</a><br><br>
              {% endfor %}
              {% endif %}
          </div>
      </div>
  </div>
 <div class="card-footer"><a href="/message_user/{{player.id}} " class="btn btn-success btn-sm">Message {{player.first_name}}</a></div>

</div>

<br><br>







{% if not user.profile %}
<h2>Create your user profile</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Submit form">
</form>
{% endif %}
{% endblock %}

Final Project/myteam/account/templates/profile.html
{% extends 'base.html' %}}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}
{% block summary %}{{summary}}{% endblock %}
{% block content %}
{% if user.profile %}
<div class="card text-center">
  <div class="card-header">@{{user.username}}</div>
  <div class="card-body text-left">
      <div class="row">
          <div class="col-4 text-center">
              <img src="{{user.profile.image.url}}" class="mx-auto d-block rounded" alt="..." style="width: 200px; height: 200px; object-fit: cover; right-margin: 100px;">
          </div>
          <div class="col-4 text-center">
              <h5 class="card-title">Details and Contact Information</h5>
              <table class=" text-left">
                  <tr>
                      <th>Name:</th>
                      <td>{{user.profile.first_name}} {{user.profile.last_name}}</td>
                  </tr>
                  <tr>
                      <th>Email Address:   </th>
                      <td>{{user.profile.email}}</td>
                  </tr>
                  <tr>
                      <th>Role:</th>
                      <td>{{user.profile.role}}</td>
                  </tr>
                  <tr>
                      <th>Position:</th>
                      <td>{{user.profile.position}}</td>
                  </tr>
            </table>
          </div>
          <div class="col-4 text-center">
               <h5 class="card-title">My Clubs</h5>

              {% if clubs %}
              {% for club in clubs %}
              <a href="clubs/{{club.id}}/details" class="btn btn-warning btn-sm" style="width: 250px;">{{club.name}} (Manager)</a><br><br>
              {% endfor %}
              {% endif %}
              {% if player_clubs %}
              {% for club in player_clubs %}
              <a href="clubs/{{club.id}}/details" class="btn btn-success btn-sm" style="width: 250px;">{{club.name}} (Player)</a><br><br>
              {% endfor %}
              {% elif not clubs and not player_clubs %}
              <p>(no current clubs)</p>
              {% endif %}
          </div>
      </div><br>
      <div class="row">
          <div class="col-4 text-center">
              <a href="{% url 'edit_profile' %}" class="btn btn-success btn-sm" style="width: 250px;">Edit Profile</a><br><br>
          </div>
          <div class="col-4 text-center">
              <a href="{% url 'clubregistration' %}" class="btn btn-success btn-sm" style="width: 250px;">Register New Club as Manager</a><br><br>
          </div>
          <div class="col-4 text-center">
              <a href="{% url 'clubs' %}" class="btn btn-success btn-sm" style="width: 250px;">Join Club as Player</a><br><br>
          </div>
      </div>
  </div>
  <div class="card-footer card-header text-muted">Messaging</div>
    <div class="card-body text-left">
        <div class="row">
            <div class="col-1"></div>
          <div class="col-4">
              <h5 class="card-title">Compose Message</h5>
              {% if clubs %}
              {% for club in clubs %}
                <a href="/compose_message/{{club.id}}" class="btn btn-warning btn-sm" style="width: 250px;">Message All {{club.name}} Players</a><br><br>
              {% endfor %}
              {% endif %}
              <a href="{% url 'compose_message' %}" class="btn btn-success btn-sm" style="width: 250px;">New Private Message</a><br><br>
          </div>
        </div>
      <div class="row">
          <div class="col-1"></div>
          <div class="col-10">
              {% if user_messages %}
              <h5 class="card-title">Inbox ({{num_unread_messages}})</h5>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">From</th>
                            <th scope="col"></th>
                            <th scope="col">Subject</th>
                            <th scope="col">Date</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for message in user_messages %}
                    <tr {% if message.status == "Unread" %} class="alert-success" {% endif %}>
                        <td class="align-middle"><img src="{{message.sender.image.url}}" class="mx-auto d-block rounded" alt="..." style="width: 50px; height: 50px; object-fit: cover; right-margin: 5px;"></td>
                        <td class="align-middle"><a href="/profile/{{message.sender.id}}" >{{message.sender}}</a></td>
                        <td class="align-middle"><a href="/read_message/{{message.id}}">{{message.subject}}</a></td>
                        <td class="align-middle">{{message.time}}</td>
                        <td class="align-middle"><a href="/read_message/{{message.id}}" class="btn btn-primary btn-sm">Open</a></td>
                        <td class="align-middle"><a href="/delete_message/{{message.id}}" class="btn btn-danger btn-sm">Delete</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
              {% endif %}
          </div>
      </div>

<!--        {% if sent_messages %}-->

<!--    <div class="row">-->
<!--        <div class="col-1"></div>-->
<!--          <div class="col-10">-->
<!--              <h5 class="card-title">Sent Messages</h5>-->
<!--                <table class="table">-->
<!--                    <thead>-->
<!--                        <tr>-->
<!--                            <th scope="col">To</th>-->
<!--                            <th scope="col"></th>-->
<!--                            <th scope="col">Subject</th>-->
<!--                            <th scope="col">Date</th>-->
<!--                            <th scope="col"></th>-->
<!--                            <th scope="col"></th>-->
<!--                        </tr>-->
<!--                    </thead>-->
<!--                    <tbody>-->
<!--                    {% for message in sent_messages %}-->
<!--                    <tr {% if message.status == "Unread" %} class="alert-danger" {% endif %}>-->
<!--                        <td class="align-middle"><img src="{{message.receiver.image.url}}" class="mx-auto d-block rounded" alt="..." style="width: 50px; height: 50px; object-fit: cover; right-margin: 5px;"></td>-->
<!--                        <td class="align-middle"><a href="/profile/{{message.receiver.id}}" >{{message.receiver}}</a></td>-->
<!--                        <td class="align-middle"><a href="/read_message/{{message.id}}">{{message.subject}}</a></td>-->
<!--                        <td class="align-middle">{{message.time}}</td>-->
<!--                        <td class="align-middle"><a href="/read_message/{{message.id}}" class="btn btn-primary btn-sm">Open</a></td>-->
<!--                        <td class="align-middle"><a href="/delete_message/{{message.id}}" class="btn btn-danger btn-sm">Delete</a></td>-->
<!--                    </tr>-->
<!--                    {% endfor %}-->
<!--                    </tbody>-->
<!--                </table>-->
<!--          </div>-->
<!--    </div>-->

<!--              {% endif %}-->
</div>

         <div class="card-footer text-muted text-center">
            <a href="{% url 'logout_view' %}">Logout</a>
       </div>
    </div>



    </div>






</div>
<p></p>
{%endif%}





{% if not user.profile %}
<h2>Create your user profile</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Submit form">
</form>
{% endif %}
{% endblock %}