Week 8 - Django/Day 2/animal-info/animals/animals/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("info.urls"))
]

Week 8 - Django/Day 2/animal-info/animals/info/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path("", views.index),
   path("family/<int:family_id>", views.family),
   path("animal/<int:animal_id>", views.animal),
   path("animals", views.animals)
]

Week 8 - Django/Day 2/animal-info/animals/info/models.py
from django.db import models

# Create your models here.
class Animal(models.Model):
    name = models.CharField(max_length=50)
    legs = models.IntegerField()
    weight = models.IntegerField()
    height = models.IntegerField()
    speed = models.IntegerField()
    family = models.ForeignKey('Family', on_delete=models.CASCADE)

class Family(models.Model):
    name = models.CharField(max_length=50)

Week 8 - Django/Day 2/animal-info/animals/info/views.py
from django.shortcuts import render
from .models import Family
from .models import Animal

# Create your views here.
def index(request):
    return render(request, "index.html")

def family(request, family_id):
    this_family = Family.objects.get(id=family_id)
    return render(request, "family.html", {"family": this_family})

def animals(request):
    all_animals = Animal.objects.all()
    return render(request, "animals.html", {"all_animals": all_animals})

def animal(request, animal_id):
    this_animal = Animal.objects.get(id=animal_id)
    return render(request, "animal.html", {"animal": this_animal})

Week 8 - Django/Day 2/animal-info/animals/info/templates/animal.html
{% extends 'index.html' %}}



{% block content %}
<h1>This is the animal page</h1>
<h2>Animal Name: {{animal.name}}</h2>
<ul>
    <li>Number of Legs: {{animal.legs}}</li>
    <li>Height: {{animal.height}}</li>
    <li>Weight: {{animal.weight}}</li>
    <li>Speed: {{animal.speed}}</li>
    <li>Family: {{animal.family.name}}</li>
</ul>


{% endblock %}

Week 8 - Django/Day 2/animal-info/animals/info/templates/animals.html
{% extends 'index.html' %}}

{% block content %}
<h1>Learn more about the following animals...</h1>
<ul>
    {% for animal in all_animals %}
    <li><a href="/animal/{{animal.id}}">{{animal.name}}</a></li>
    {% endfor %}
</ul>

{% endblock %}

Week 8 - Django/Day 2/animal-info/animals/info/templates/family.html
{% extends 'index.html' %}}



{% block content %}
<h1>This is the family page</h1>
<h3>Family Type: {{family.name}}</h3>
<h3>Family ID: {{family.id}}</h3>
<h3>Members of this family...</h3>
{% for animal in family.animal_set.all %}
<p>{{animal.name}}</p>
{% endfor %}

{% endblock %}

Week 8 - Django/Day 2/animal-info/animals/info/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

 {% block content %}
 Hey this is the index
 {% endblock %}
</body>
</html>